version: "3.8"

networks:
  bullmq-poc:
    driver: bridge

services:
  cache:
    image: 'redis'
    container_name: 'redis-server'
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - redis-data:/data
    restart: always
    networks:
      - bullmq-poc
  redis-ide:
    image: redis/redisinsight:latest
    container_name: redis-ide
    ports:
      - 5540:5540
    networks:
      - bullmq-poc

    
volumes:
  redis-data:
    driver: local

  